name: CI DevOps PFE

on:
  push:
    branches: [ "Team6/profile-features", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: make install

      - name: Database migration
        run: cd api-node && node src/database/migrate.js

      - name: Run Tests & Coverage
        run: make test

      - name: Build Frontend
        run: cd client-react && npm run build
