name: DevOps_Pipeline_CI

on:
  push:
    branches: [ "main", "Team6/profile-features" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Database Migration
        run: cd api-node && node src/database/migrate.js

      - name: Run Tests & Coverage
        run: cd api-node && npm test
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install & Run Tests
        run: |
          cd api-node
          npm install
          npm test # Lance les tests automatiques et le coverage

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build React
        run: |
          cd client-react
          npm install
          npm run build # Vérifie que le build ne plante pas